"""настраиваемые способы оплаты

Revision ID: 2206adc074f0
Revises: 93ba54b62e72
Create Date: 2026-09-06 12:00:27.161003
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2206adc074f0'
down_revision: str | None = '93ba54b62e72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True, comment='Что сделать жильцу — показывается на экране оплаты'),
    sa.Column('requisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Произвольные реквизиты: банк, ИИК, БИК, получатель'),
    sa.Column('qr_url', sa.String(length=500), nullable=True),
    sa.Column('deeplink_template', sa.String(length=500), nullable=True, comment='Шаблон ссылки с подстановками {account}, {amount}, {period}'),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_methods_org', 'payment_methods', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_methods_org', table_name='payment_methods')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
