"""волна 2: billing

Revision ID: 63a88d3cc888
Revises: 08b30e32cd95
Create Date: 2026-09-06 10:23:02.886028
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '63a88d3cc888'
down_revision: str | None = '08b30e32cd95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'year', 'month', name='uq_billing_period')
    )
    op.create_table('service_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='м3, кВт·ч, м2, мес'),
    sa.Column('is_metered', sa.Boolean(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_service_type_name')
    )
    op.create_index('ix_service_types_organization', 'service_types', ['organization_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('external_number', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False, comment='Отрицательный — задолженность'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_number', name='uq_account_external')
    )
    op.create_index('ix_accounts_apartment', 'accounts', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_accounts_external_number'), 'accounts', ['external_number'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('billing_period_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['billing_period_id'], ['billing_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'billing_period_id', name='uq_invoice_account_period')
    )
    op.create_index('ix_invoices_account', 'invoices', ['account_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('payment_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True, comment='NULL, если лицевой счёт из реестра не опознан'),
    sa.Column('raw_account_number', sa.String(length=50), nullable=True, comment='Номер счёта как он пришёл в реестре'),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=25), nullable=False),
    sa.Column('payer_name', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('unallocated_amount', sa.Integer(), nullable=False, comment='Не разнесённый по квитанциям остаток'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_payment_fact_ref')
    )
    op.create_index('ix_payment_facts_account', 'payment_facts', ['account_id'], unique=False)
    op.create_index('ix_payment_facts_unmatched', 'payment_facts', ['organization_id', 'is_matched'], unique=False)
    op.create_table('charges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('billing_period_id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Тенге'),
    sa.Column('volume', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('tariff', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['billing_period_id'], ['billing_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_charges_invoice', 'charges', ['invoice_id'], unique=False)
    op.create_index('ix_charges_period_account', 'charges', ['billing_period_id', 'account_id'], unique=False)
    op.create_table('payment_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('receipt_ref', sa.String(length=100), nullable=True, comment='Номер операции из чека Kaspi'),
    sa.Column('source', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_fact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_fact_id'], ['payment_facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_claims_invoice', 'payment_claims', ['invoice_id'], unique=False)
    op.create_table('reconciliation_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_fact_id', sa.UUID(), nullable=True),
    sa.Column('payment_claim_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=25), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_claim_id'], ['payment_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_fact_id'], ['payment_facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_invoice', 'reconciliation_log', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reconciliation_invoice', table_name='reconciliation_log')
    op.drop_table('reconciliation_log')
    op.drop_index('ix_payment_claims_invoice', table_name='payment_claims')
    op.drop_table('payment_claims')
    op.drop_index('ix_charges_period_account', table_name='charges')
    op.drop_index('ix_charges_invoice', table_name='charges')
    op.drop_table('charges')
    op.drop_index('ix_payment_facts_unmatched', table_name='payment_facts')
    op.drop_index('ix_payment_facts_account', table_name='payment_facts')
    op.drop_table('payment_facts')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_account', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_accounts_external_number'), table_name='accounts')
    op.drop_index('ix_accounts_apartment', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_service_types_organization', table_name='service_types')
    op.drop_table('service_types')
    op.drop_table('billing_periods')
    # ### end Alembic commands ###
