"""хранилище файлов

Revision ID: 6bbf497f89f5
Revises: 2206adc074f0
Create Date: 2026-09-06 12:18:12.473079
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6bbf497f89f5'
down_revision: str | None = '2206adc074f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=600), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_attached', sa.Boolean(), nullable=False, comment='Привязан ли файл к объекту'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_stored_files_owner', 'stored_files', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stored_files_owner', table_name='stored_files')
    op.drop_table('stored_files')
    # ### end Alembic commands ###
